### PR TITLE
NOMRG test new branch

### PR DESCRIPTION
**Pull request by adrinjalali**

### CODE REVIEW

**Comment by thomasjpfan** [comment]
Issue is coming from https://github.com/matthew-brett/multibuild/issues/309

**Comment by thomasjpfan** [comment]
The last remaining test failure will be fixed when https://github.com/scikit-learn/scikit-learn/pull/17073 get merged.

**Comment by adrinjalali** [comment]
@thomasjpfan was it this error you were trying to fix?

```
Traceback (most recent call last):
  File "/io/multibuild/supported_wheels.py", line 15, in <module>
    from pip.pep425tags import get_supported
ModuleNotFoundError: No module named 'pip.pep425tags'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/io/multibuild/supported_wheels.py", line 17, in <module>
    from pip._internal.pep425tags import get_supported
ModuleNotFoundError: No module named 'pip._internal.pep425tags'
ERROR: You must give at least one requirement to install (maybe you meant "pip install https://pypi.python.org/simple"?)
```

**Comment by thomasjpfan** [comment]
That error appeared when using a previous version of multibuild. Those lines of code no longer exist in `supperted_wheels.py` (on the `devel` branch)

**Pull request merged**
