### PR TITLE
Preparing a beta release: set BUILD_COMMIT to 0.22b1

### PR DESCRIPTION
**Pull request by adrinjalali**
Preparing a beta release. The branch and the tag are already on the scikit-learn repo.

### CODE REVIEW

**Comment by jnothman** [comment]
We gave up on betas a few years back, jumping to rcs. But this is good too!

**Comment by adrinjalali** [comment]
I opted for a beta since some issues are not solved, and as you mentioned we still may add some features. But the main reason, is that I didn't want my first release to be an RC. This is partly beta because I'm still learning the steps and didn't want to accidentally release something which people may rely on while there's a chance that they shouldn't ;)

**Comment by jnothman** [comment]
Minor bug fixes, doc changes, warnings for API changes, etc can potentially
be added between rc and release. Features probably shouldn't be. At some
point we'll need to just cut and ship.

**Comment by adrinjalali** [comment]
I can remove the beta tag and replace it with an `rc1` if you prefer.

**Comment by jnothman** [comment]
Don't mind really. It's more about how we communicate with our users.

**Comment by amueller** [comment]
yeah someone might ask "what's the difference between an rc and a beta". So I'm +0.5 for rc

**Comment by adrinjalali** [comment]
This now passes the CI and has 0.22rc1 as the version tag.

If I understand correctly, this PR needs to be merged so that the wheels are uploaded to wheels.scipy.org, so that I can continue with the release?

**Comment by rth** [comment]
Do we want to add Python 3.8 wheels as well for the rc https://github.com/MacPython/scikit-learn-wheels/issues/34? As far as I understood tests were passing locally, so it's mostly about adding the corresponding CI entries in this repo I think.

**Comment by adrinjalali** [comment]
Do we need it for the RC? I rather get the RC out, then add the few things which we need to add for the release.

**Comment by jnothman** [comment]
So the plan is to put an RC out there, try to merge the Logistic
preconditioning, then put out another RC for people to try that change?

**Comment by adrinjalali** [comment]
The next one can be an RC2 or a release. I'm not sure if the preconditioning needs to be in an RC first, but I'm happy to do an RC2 with that and some other fixes we have in the backlog before the release if that's what you think is appropriate.

**Comment by jnothman** [comment]
Let's merge this and get it onto wheels.scipy.

**Comment by jnothman** [comment]
But we've also made a few changes since this was tagged, so it would be good practice to then make another RC afterwards

**Pull request merged**
