### PR TITLE
[WIP] Adds python 3.8 wheels

### PR DESCRIPTION
**Pull request by thomasjpfan**
Adds python 3.8 wheels

Closes https://github.com/MacPython/scikit-learn-wheels/issues/34

### CODE REVIEW

**Comment by thomasjpfan** [comment]
Update: `test_scale_and_stability` is failing on 64 bit windows.

**Comment by thomasjpfan** [comment]
Moving to 1.2.2 resolves the issue so this seems to be scipy 1.3.* issue on windows 64bit

**Comment by jnothman** [comment]
So I suppose this will work if we change the BUILD_COMMIT to 0.20.X

**Comment by jnothman** [comment]
yes, master not 0.22.X :)

**Comment by thomasjpfan** [comment]
YESSS all the wheels can be built on master!

**Comment by adrinjalali** [comment]
Awesome, thanks @thomasjpfan . @rth does it look good to you?

**Comment by jnothman** [comment]
I think my review request was accidental

**Comment by adrinjalali** [comment]
@jnothman could you please then merge this? (I don't have permissions here)

**Pull request merged**
