### PR TITLE
BUILD_COMMIT=0.20.3

### PR DESCRIPTION
**Pull request by jnothman**

### CODE REVIEW

**Comment by jnothman** [comment]
README.rst implies I don't need to do this as a PR. Do I just merge?

**Comment by rth** [comment]
We would still prefer to know that CI passes I imagine? That's easier in a PR...

**Comment by jnothman** [comment]
Okay. I'm not sure I'll manage to do twine today. I'm sure that's just what @ogrisel wants to do to cap off the sprint!

**Comment by jnothman** [comment]
Somehow the openmp requirement has landed up in 0.20.3? Is that a change in scikit-learn, or in scikit-learn-wheels? (@jeremiedbb?)

**Comment by jnothman** [comment]
Ahhh I see. The daily build runs are running in this PR too. That's a bug, but I can merge safely if only those runs continue to fail.

**Comment by jnothman** [comment]
Merging

**Pull request merged**
