### PR TITLE
Clean-up references to appveyor and travis

### PR DESCRIPTION
**Pull request by ogrisel**
Those files are no longer used.

### CODE REVIEW

**Comment by adrinjalali** [comment]
interesting, why does appveyor try to run the PR if configs are not there? I thought it would just not run.

**Comment by ogrisel** [comment]
Because it was still registered to monitor this project. I just logged in to delete the project on appveyor.

**Comment by ogrisel** [comment]
Ok let's see if merging a pull-request did re-activate the scheduled jobs in the devops UI.

**Comment by ogrisel** [comment]
That did not work but bf605e22349c4fd62bbf4fc4d41f6761eb61536c did.

**Comment by adrinjalali** [comment]
thanks @ogrisel

**Pull request merged**
